using System;
using System.Windows.Controls;
using Pinpoint.Core;
using Pinpoint.Win.ViewModels;

namespace Pinpoint.Win.Views
{
    /// <summary>
    /// Interaction logic for PluginTabItem.xaml
    /// </summary>
    public partial class PluginTabItem : TabItem
    {
        public PluginTabItem(AbstractPlugin plugin)
        {
            InitializeComponent();
            DataContext = App.Current.PluginTabItemViewModel;
            Model.Plugin = plugin;
        }

        public PluginTabItemViewModel Model => (PluginTabItemViewModel)DataContext;

        private void PluginSettings_OnAutoGeneratedColumns(object? sender, EventArgs e)
        {
            var grid = sender as DataGrid;
            if (!Model.Plugin.State.HasModifiableSettings)
            {
                grid.Columns[0].IsReadOnly = true;
            }
            else
            {
                grid.CanUserAddRows = true;
                grid.CanUserDeleteRows = true;
                grid.CanUserReorderColumns = true;
            }
        }
    }
}
