using System;
using System.Windows.Controls;
using System.Windows.Input;
using Pinpoint.Core;
using Pinpoint.Win.ViewModels;

namespace Pinpoint.Win.Views
{
    /// <summary>
    /// Interaction logic for PluginTabItem.xaml
    /// </summary>
    public partial class PluginTabItem : TabItem
    {
        public PluginTabItem(IPlugin plugin)
        {
            InitializeComponent();
            DataContext = App.Current.PluginTabItemViewModel;
            Model.Plugin = plugin;
        }

        public PluginTabItemViewModel Model => (PluginTabItemViewModel) DataContext;

        private void PluginSettings_OnAutoGeneratedColumns(object? sender, EventArgs e)
        {
            var grid = sender as DataGrid;
            grid.Columns[0].IsReadOnly = true;
        }
    }
}
